version: '3.8'

services:
  cat:
    image: celaraze/cat:latest
    container_name: cat
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cat_database:/var/www/database/data

volumes:
  cat_database: