version: '3.8'

services:
  cat:
    image: celaraze/cat:latest
    container_name: cat
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - cat_database:/var/www/database/data
      - cat_storage:/var/www/storage/app/public

volumes:
  cat_database:
  cat_storage:
